FROM ubuntu


##############CORS SETUP START#############
# Here you have to put your Frontend Domain and Port.
# If your frontend running on port 80 then please leave it blank
# if your forntend running on custom port use : before the port. 
# e.g : for port 8081 ":8081" instead of "8081"
# Dont use port 8080 as backend running on this port

ENV SERVER_NAME=10.8.215.16
ENV SERVER_PORT=

##############CORS SETUP END#############

##########DATABASE CONFIG START###########

ENV DB_USERNAME=java
ENV DB_PASSWORD=java_pass
ENV DB_NAME=javadb
ENV DB_HOST=10.8.215.16
ENV DB_PORT=3306

##########DATABASE CONFIG END############

##########REPOSITORY CONFIG START########

ENV GIT_REPO=https://github.com/Team-Cloudboost/sping-boot-docker.git
ENV GIT_BRANCH=main
ENV GIT_FOLDER=app/backend

##########REPOSITORY CONFIG END##########

ENV TZ=Asia/Dhaka \
    DEBIAN_FRONTEND=noninteractive

WORKDIR /project

RUN apt update; \
    apt install openjdk-8-jdk maven git wget -y; \
    cd /project; \
    git init; \
    git remote add origin $GIT_REPO; \
    git fetch origin; \
    git checkout origin/$GIT_BRANCH -- $GIT_FOLDER; \
    sed -i 's,@CrossOrigin(origins =.*,@CrossOrigin(origins = "http://'"$SERVER_NAME$SERVER_PORT"'"),g' /project/app/backend/src/main/java/com/bezkoder/spring/datajpa/controller/TutorialController.java; \
    sed -i "s,spring.datasource.url=.*,spring.datasource.url= jdbc:mysql://$DB_HOST:$DB_PORT/$DB_NAME?useSSL=false,g" /project/app/backend/src/main/resources/application.properties; \
    sed -i "s,spring.datasource.username=.*,spring.datasource.username= $DB_USERNAME,g" /project/app/backend/src/main/resources/application.properties; \
    sed -i "s,spring.datasource.password=.*,spring.datasource.password= $DB_PASSWORD,g" /project/app/backend/src/main/resources/application.properties; \
    cd /project/$GIT_FOLDER; \
    mvn clean install; \
    cd /project; mkdir tomcat; \
    wget -O tomcat.tar.gz https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.68/bin/apache-tomcat-9.0.68.tar.gz; \
    tar -xvf tomcat.tar.gz -C tomcat; \
    mv ./tomcat/*/* ./tomcat; \
    cp /project/$GIT_FOLDER/target/spring-boot-data-jpa.war ./tomcat/webapps/; 

ENTRYPOINT ["sh", "/project/tomcat/bin/catalina.sh", "run"]

EXPOSE 8080