FROM nginx:alpine

#######CONFIG START#########
ENV SERVER_NAME=10.8.215.16
ENV REPO_LINK=https://github.com/Team-Cloudboost/sping-boot-docker.git
ENV REPO_BRANCH=main
ENV REPO_FOLDER=app/frontend
#######CONFIG END###########

WORKDIR /project

RUN apk add git npm; \
    cd /project; \
    git init; \
    git remote add origin $REPO_LINK; \
    git fetch origin; \
    git checkout origin/$REPO_BRANCH -- $REPO_FOLDER; \
    cd $REPO_FOLDER; \
    sed -i 's,localhost,'"$SERVER_NAME"',g' src/http-common.js; \
    npm install; \
    npm run build; \
    rm -rf usr/share/nginx/html/*; \
    cp -rf build/* /usr/share/nginx/html;

EXPOSE 80
