FROM ubuntu

######DATBASE COFIG START##################
ENV MYSQL_ROOT_PASSWORD=StrongPass
ENV MYSQL_DATABASE=javadb
ENV MYSQL_USER=java
ENV MYSQL_PASSWORD=java_pass
######DATBASE COFIG END####################

ENV TZ=Asia/Dhaka \
    DEBIAN_FRONTEND=noninteractive

RUN apt update; apt install mysql-server -y; \
    /etc/init.d/mysql start; \
    mysql -e "CREATE DATABASE ${MYSQL_DATABASE};";\
    mysql -e "CREATE USER '${MYSQL_USER}'@'%' IDENTIFIED BY '${MYSQL_PASSWORD}';"; \
    mysql -e "GRANT ALL ON ${MYSQL_DATABASE}.* TO '${MYSQL_USER}'@'%';"; \
    mysql -e "ALTER USER 'root'@'localhost' IDENTIFIED WITH caching_sha2_password BY '${MYSQL_ROOT_PASSWORD}';" \
    sed -i "s,bind-address.*,bind-address = 0.0.0.0,g" /etc/mysql/mysql.conf.d/mysqld.cnf; 

ENTRYPOINT [ "sh", "/etc/init.d/mysql", "start" ]

EXPOSE 3306