FROM ubuntu:20.04

ARG SERVER_NAME
ARG SERVER_PORT
ARG DB_USERNAME
ARG DB_PASSWORD
ARG DB_USERNAME
ARG DB_HOST
ARG DB_PORT

ARG GIT_REPO
ARG GIT_BRANCH
ARG GIT_FOLDER

ENV TZ=Asia/Dhaka \
    DEBIAN_FRONTEND=noninteractive

WORKDIR /project

RUN apt update; \
    apt install openjdk-8-jdk maven git wget -y; \
    cd /project; \
    git init; \
    git remote add origin $GIT_REPO; \
    git fetch origin; \
    git checkout origin/$GIT_BRANCH -- $GIT_FOLDER; \


