FROM ubuntu

######DATBASE COFIG START##################
ENV MYSQL_ROOT_PASSWORD=StrongPass
ENV MYSQL_DATABASE=javadb
ENV MYSQL_USER=java
ENV MYSQL_PASSWORD=java_pass
######DATBASE COFIG END####################

RUN /etc/init.d/mysql start; \
    mysql -e "ALTER USER 'root'@'localhost' IDENTIFIED WITH caching_sha2_password BY '${MYSQL_ROOT_PASSWORD}';"

EXPOSE 3306