FROM nginx:alpine

ARG SERVER_NAME
ARG REPO_LINK
ARG REPO_BRANCH
ARG REPO_FOLDER
WORKDIR /project

RUN apk add git npm; \
    cd /project; \
    git init; \
    git remote add origin $REPO_LINK; \
    git fetch origin; \
    git checkout origin/$REPO_BRANCH -- REPO_FOLDER; \
    cd $REPO_FOLDER; \
    sed -i 's,localhost,$SERVER_NAME,g' src/http-common.js; \
    npm install; \
    npm run build; \
    rm -rf usr/share/nginx/html/*; \
    cp -rf build/* /usr/share/nginx/html;
