version: '3.3'

services:
  db:
    image: teamcloudboost/spring-boot:database
    ports:
      - 3306:3306
    container_name: spring-boot-database
    restart: unless-stopped
    healthcheck:
            test: mysqladmin ping -h 127.0.0.1 -uroot --password=$MYSQL_ROOT_PASSWORD
            timeout: 20s
            retries: 10
  backend:
    image: teamcloudboost/spring-boot:backend
    ports:
      - 8080:8080
    container_name: spring-boot-backend
    restart: unless-stopped
    depends_on:
        - db
    
          
        
  fronend:
    image: teamcloudboost/spring-boot:frontend
    ports:
      - 80:80
    container_name: spring-boot-frontend
    restart: unless-stopped
    depends_on:
      - db
      - backend
    
  
    
