version: "2.1"
services:
    api:
        image: teamcloudboost/spring-boot:backend
        container_name: spring-boot-backend
        ports:
            - "8080:8080"
        depends_on:
            db:
                condition: service_healthy
    db:
        container_name: spring-boot-database
        image: teamcloudboost/spring-boot:database
        ports:
            - "3306"
        entrypoint: [ "mysqld"]
        healthcheck:
            test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-ujava", "-p$$MYSQL_PASSWORD"]
            timeout: 20s
            retries: 10
    


