version: '3.3'

services:
  db:
    image: teamcloudboost/spring-boot:database
    ports:
      - 3306:3306
    container_name: spring-boot-database
    restart: unless-stopped
  backend:
    image: teamcloudboost/spring-boot:backend
    ports:
      - 8080:8080
    container_name: spring-boot-backend
    restart: unless-stopped
    entrypoint: ["mysqld"]
    depends_on:
      - db
  fronend:
    image: teamcloudboost/spring-boot:frontend
    ports:
      - 80:80
    container_name: spring-boot-frontend
    restart: unless-stopped
    depends_on:
      - db
      - backend
  
    
